In [1]:
from numpy import full


sequence1 = "GCATGCG"
sequence2 = "GATTACA"

NUMBER_OF_ROWS = len(sequence1) + 1
NUMBER_OF_COLUMNS = len(sequence2) + 1

scoring_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],0)
print("Scoring array:\n",scoring_array)

traceback_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],"-")
print("Traceback array:\n",traceback_array)


Scoring array:
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
Traceback array:
 [['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-']]


In [2]:
from IPython.core.display import HTML,display
import pandas as pd

def table_from_array(data_array, row_labels,col_labels):
    """Show an HTML table from a 2d numpy array"""
    df = pd.DataFrame(data_array,index=row_labels,columns=col_labels)
    table_html = df.to_html()
    return HTML(table_html)

In [3]:
row_labels = [label for label in "-"+ sequence1]
column_labels = [label for label in "-"+ sequence2]

print("Scoring array:")
display(table_from_array(scoring_array,row_labels,column_labels))
print("Traceback array:")
display(table_from_array(traceback_array,row_labels,column_labels))

Scoring array:


Traceback array:


In [4]:
up_arrow = "\u2191"
right_arrow = "\u2192"
down_arrow = "\u2193"
left_arrow = "\u2190"
down_right_arrow = "\u2198"
up_left_arrow = "\u2196"

print("Up arrow",up_arrow)
print("Right arrow",right_arrow)
print("Down arrow",down_arrow)
print("Left arrow",left_arrow)
print("Down Left arrow",down_right_arrow)
print("Up Left arrow",up_left_arrow)


Up arrow ↑
Right arrow →
Down arrow ↓
Left arrow ←
Down Left arrow ↘
Up Left arrow ↖


In [5]:

NUMBER_OF_ROWS = len(sequence1) + 1 
NUMBER_OF_COLUMNS = len(sequence2) + 1
row_labels = [label for label in "-"+sequence1]
column_labels = [label for label in "-"+sequence2]


scoring_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],0)
traceback_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],"-")


arrow = "-"

match_bonus = 1


In [6]:
for row in range(NUMBER_OF_ROWS):
    for col in range(NUMBER_OF_COLUMNS):    
        #set first row and column to zero
        if row ==0 or col == 0:
            score=0
            arrow='-'
            #elif col==1:
            #    arrow=up_arrow
          #  elif row==1:
          #      arrow=left_arrow    
        else: 

            cell_to_the_left = scoring_array[row,col-1]
            from_left_score = cell_to_the_left 


            above_cell = scoring_array[row-1,col]
            from_above_score = above_cell 
            
            diagonal_left_cell = scoring_array[row-1,col-1]

            if sequence1[row-1] == sequence2[col-1]:
                diagonal_left_cell_score = diagonal_left_cell + match_bonus
            else:
                diagonal_left_cell_score = diagonal_left_cell
            
            score = max([from_left_score,from_above_score,diagonal_left_cell_score])       
            

            
            #traceback path of current element
            if score == from_left_score:
                arrow = left_arrow     
            elif score == from_above_score:
                arrow = up_arrow                
            elif score == diagonal_left_cell_score:
                arrow = up_left_arrow
                
                
            


        if(row==1):
            arrow=left_arrow
        if(col==1):
            arrow=up_arrow
        if(row==1 and col==1):
            arrow=up_left_arrow
                
        traceback_array[row,col]=arrow    
        scoring_array[row,col] = score

traceback_array[0,1]='-'
traceback_array[1,0]='-' 
display(table_from_array(scoring_array,row_labels,column_labels))  
display(table_from_array(traceback_array,row_labels,column_labels))            

In [7]:
def traceback_alignment(traceback_array,seq1,seq2,up_arrow = "\u2191" ,\
                        left_arrow="\u2190",up_left_arrow="\u2196",stop="-"):


    NUMBER_OF_ROWS = len(sequence1) + 1 
    NUMBER_OF_COLUMNS = len(sequence2) + 1 
    
    row = len(sequence1)
    col = len(sequence2)
    arrow = traceback_array[row,col]
    aligned_seq1 = ""
    aligned_seq2 = ""
    alignment_indicator = ""
    while arrow != "-":

            arrow = traceback_array[row,col]

            
            if arrow == up_arrow: 


                aligned_seq2 = "-"+aligned_seq2 
                aligned_seq1 = sequence1[row-1] + aligned_seq1
                alignment_indicator = " "+alignment_indicator
                row -=1
                            
            elif arrow == up_left_arrow:


                seq1_character = sequence1[row-1]
                seq2_character = sequence2[col-1]
                aligned_seq1 = sequence1[row-1] + aligned_seq1
                aligned_seq2 = sequence2[col-1] + aligned_seq2
                if seq1_character == seq2_character:
                    alignment_indicator = "|"+alignment_indicator
                else:
                    alignment_indicator = " "+alignment_indicator
                row -=1
                col -=1
                
            elif arrow == left_arrow:

                aligned_seq1 = "-"+aligned_seq1
                aligned_seq2 = sequence2[col-1] + aligned_seq2
                alignment_indicator = " "+alignment_indicator
                col -=1
                
            elif arrow == stop:
                break
                
                
    print(aligned_seq1)
    print(alignment_indicator)
    print(aligned_seq2)

            
    return aligned_seq1,aligned_seq2


traceback_alignment(traceback_array,sequence1,sequence2)

print(scoring_array[NUMBER_OF_ROWS-1][NUMBER_OF_COLUMNS-1])

GCATG--CG-
| ||   |  
G-AT-TAC-A
4


In [8]:
##differentiating Needleman-Wunsch

In [18]:
#initialization
gradient=full([NUMBER_OF_ROWS+2,NUMBER_OF_COLUMNS+2],0)
gradient[NUMBER_OF_ROWS+1,NUMBER_OF_COLUMNS+1]=1.0
backtracking=full([NUMBER_OF_ROWS+2,NUMBER_OF_COLUMNS+2,3],0)
backtracking[NUMBER_OF_ROWS+1,NUMBER_OF_COLUMNS+1,2]=1.0
print("Gradient array:\n",gradient)
print("Backtracking array:\n",backtracking)

Gradient array:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]]
Backtracking array:
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 

In [23]:
substitution_matrix=full([len(sequence1), len(sequence2)],0)
for i in range(NUMBER_OF_ROWS-1):
    for j in range(NUMBER_OF_COLUMNS-1):
        if sequence1[i]!=sequence2[j]:
            substitution_matrix[i,j]=1  #1 if different
        else:                           #0 if same
            substitution_matrix[i,j]=0
print("substitution matrix: \n",substitution_matrix)            

substitution matrix: 
 [[0 1 1 1 1 1 1]
 [1 1 1 1 1 0 1]
 [1 0 1 1 0 1 0]
 [1 1 0 0 1 1 1]
 [0 1 1 1 1 1 1]
 [1 1 1 1 1 0 1]
 [0 1 1 1 1 1 1]]


In [ ]:
for i in range(NUMBER_OF_ROWS-1):
    for j in range(NUMBER_OF_COLUMNS-1):
        