In [1]:
from numpy import full


sequence1 = "AATAAAAAA"
sequence2 = "TTTAAAATAAA"

NUMBER_OF_ROWS = len(sequence1) + 1
NUMBER_OF_COLUMNS = len(sequence2) + 1

scoring_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],0)
print("Scoring array:\n",scoring_array)

traceback_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],"-")
print("Traceback array:\n",traceback_array)


Scoring array:
 [[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]
Traceback array:
 [['-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-']]


In [2]:
from IPython.core.display import HTML,display
import pandas as pd

def table_from_array(data_array, row_labels,col_labels):
    """Show an HTML table from a 2d numpy array"""
    df = pd.DataFrame(data_array,index=row_labels,columns=col_labels)
    table_html = df.to_html()
    return HTML(table_html)

In [3]:
row_labels = [label for label in "-"+ sequence1]
column_labels = [label for label in "-"+ sequence2]

print("Scoring array:")
display(table_from_array(scoring_array,row_labels,column_labels))
print("Traceback array:")
display(table_from_array(traceback_array,row_labels,column_labels))

Scoring array:


Traceback array:


In [4]:
up_arrow = "\u2191"
right_arrow = "\u2192"
down_arrow = "\u2193"
left_arrow = "\u2190"
down_right_arrow = "\u2198"
up_left_arrow = "\u2196"

print("Up arrow",up_arrow)
print("Right arrow",right_arrow)
print("Down arrow",down_arrow)
print("Left arrow",left_arrow)
print("Down Left arrow",down_right_arrow)
print("Up Left arrow",up_left_arrow)


Up arrow ↑
Right arrow →
Down arrow ↓
Left arrow ←
Down Left arrow ↘
Up Left arrow ↖


In [5]:

NUMBER_OF_ROWS = len(sequence1) + 1 
NUMBER_OF_COLUMNS = len(sequence2) + 1
row_labels = [label for label in "-"+sequence1]
column_labels = [label for label in "-"+sequence2]


scoring_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],0)
traceback_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],"-")


arrow = "-"

match_bonus = 1


In [6]:
for row in range(NUMBER_OF_ROWS):
    for col in range(NUMBER_OF_COLUMNS):    
        #set first row and column to zero
        if row ==0 or col == 0:
            score=0
            arrow='-'
        else: 

            cell_to_the_left = scoring_array[row,col-1]
            from_left_score = cell_to_the_left 
             

            above_cell = scoring_array[row-1,col]
            from_above_score = above_cell 
            
            diagonal_left_cell = scoring_array[row-1,col-1]

            if sequence1[row-1] == sequence2[col-1]:
                diagonal_left_cell_score = diagonal_left_cell + match_bonus
            else:
                diagonal_left_cell_score = diagonal_left_cell
            
            score = max([from_left_score,from_above_score,diagonal_left_cell_score])       
            

            
            #traceback path of current element
            if score == diagonal_left_cell_score:
                arrow = up_left_arrow            
            elif score == from_left_score:
                arrow = left_arrow
            elif score == from_above_score:
                arrow = up_arrow

                
        traceback_array[row,col]=arrow    
        scoring_array[row,col] = score
        
display(table_from_array(scoring_array,row_labels,column_labels))  
display(table_from_array(traceback_array,row_labels,column_labels))            

In [7]:
def traceback_alignment(traceback_array,seq1,seq2,up_arrow = "\u2191" ,\
                        left_arrow="\u2190",up_left_arrow="\u2196",stop="-"):


    NUMBER_OF_ROWS = len(sequence1) + 1 
    NUMBER_OF_COLUMNS = len(sequence2) + 1 
    
    row = len(sequence1)
    col = len(sequence2)
    arrow = traceback_array[row,col]
    aligned_seq1 = ""
    aligned_seq2 = ""
    alignment_indicator = ""
    while arrow is not "-":

            arrow = traceback_array[row,col]

            
            if arrow == up_arrow: 


                aligned_seq2 = "-"+aligned_seq2 
                aligned_seq1 = sequence1[row-1] + aligned_seq1
                alignment_indicator = " "+alignment_indicator
                row -=1
                            
            elif arrow == up_left_arrow:


                seq1_character = sequence1[row-1]
                seq2_character = sequence2[col-1]
                aligned_seq1 = sequence1[row-1] + aligned_seq1
                aligned_seq2 = sequence2[col-1] + aligned_seq2
                if seq1_character == seq2_character:
                    alignment_indicator = "|"+alignment_indicator
                else:
                    alignment_indicator = " "+alignment_indicator
                row -=1
                col -=1
                
            elif arrow == left_arrow:

                aligned_seq1 = "-"+aligned_seq1
                aligned_seq2 = sequence2[col-1] + aligned_seq2
                alignment_indicator = " "+alignment_indicator
                col -=1
                
            elif arrow == stop:
                break
                
                
    print(aligned_seq1)
    print(alignment_indicator)
    print(aligned_seq2)

            
    return aligned_seq1,aligned_seq2


traceback_alignment(traceback_array,sequence1,sequence2)

print(scoring_array[NUMBER_OF_ROWS-1][NUMBER_OF_COLUMNS-1])

AATAAAAAA
|| || |||
AA-AATAAA
7


<>:14: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:14: SyntaxWarning: "is not" with a literal. Did you mean "!="?
C:\Users\zg\AppData\Local\Temp/ipykernel_2024/492216035.py:14: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while arrow is not "-":
