In [1]:
from numpy import full
import numpy as np

sequence1 = "MYSTRING"
sequence2 = "GUITARSTRINGS"

alphabet="ABCDEFGHIJKLMNOPQRSTUVWZ"

NUMBER_OF_ROWS = len(sequence1) + 1
NUMBER_OF_COLUMNS = len(sequence2) + 1

scoring_array=np.zeros((NUMBER_OF_ROWS,NUMBER_OF_COLUMNS), dtype=float)

traceback_array=np.zeros((NUMBER_OF_ROWS,NUMBER_OF_COLUMNS), dtype=float)

#scoring_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],0.00000)
print("Scoring array:\n",scoring_array)


#traceback_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],"-")
print("Traceback array:\n",traceback_array)


Scoring array:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Traceback array:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [2]:
import numpy
numpy.random.seed(3)
numpy.random.rand()

0.5507979025745755

In [3]:
import numpy as np
alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
print(len(alphabet))
File_data=np.zeros((26,26), dtype=float)
for i in range (26):
    for j in range (26):
        File_data[i][j]=numpy.random.rand()

####delete
#File_data=np.zeros((26,26), dtype=float)
for i in range (26):
    File_data[i][i]=1

print(NUMBER_OF_ROWS)
print(NUMBER_OF_COLUMNS)

print(len(File_data))
#print(File_data)

26
9
14
26


In [4]:
from IPython.core.display import HTML,display
import pandas as pd

def table_from_array(data_array, row_labels,col_labels):
    """Show an HTML table from a 2d numpy array"""
    df = pd.DataFrame(data_array,index=row_labels,columns=col_labels)
    table_html = df.to_html()
    return HTML(table_html)

In [5]:
row_labels = [label for label in "-"+ sequence1]
column_labels = [label for label in "-"+ sequence2]

alpha_table_rows=[label for label in alphabet]
alpha_table_cols=[label for label in alphabet]

print("Alphabet array:")
display(table_from_array(File_data,alpha_table_rows,alpha_table_cols))

print("Scoring array:")
display(table_from_array(scoring_array,row_labels,column_labels))
print("Traceback array:")
display(table_from_array(traceback_array,row_labels,column_labels))

Alphabet array:


Scoring array:


Traceback array:


In [6]:
up_arrow = "\u2191"
right_arrow = "\u2192"
down_arrow = "\u2193"
left_arrow = "\u2190"
down_right_arrow = "\u2198"
up_left_arrow = "\u2196"

print("Up arrow",up_arrow)
print("Right arrow",right_arrow)
print("Down arrow",down_arrow)
print("Left arrow",left_arrow)
print("Down Left arrow",down_right_arrow)
print("Up Left arrow",up_left_arrow)


Up arrow ↑
Right arrow →
Down arrow ↓
Left arrow ←
Down Left arrow ↘
Up Left arrow ↖


In [7]:

NUMBER_OF_ROWS = len(sequence1) + 1 
NUMBER_OF_COLUMNS = len(sequence2) + 1
row_labels = [label for label in "-"+sequence1]
column_labels = [label for label in "-"+sequence2]


scoring_array=np.zeros((NUMBER_OF_ROWS,NUMBER_OF_COLUMNS), dtype=float)



traceback_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],"-")


arrow = "-"

match_bonus = 1
gap_penalty=0.1


In [8]:
for row in range(NUMBER_OF_ROWS):
    for col in range(NUMBER_OF_COLUMNS):    
        #set first row and column to zero
        if row ==0 and col == 0:
            score=0
            arrow='-'
        elif row == 0:

            previous_score = scoring_array[row,col - 1]
            
            score = previous_score + gap_penalty
            arrow = left_arrow
        elif col == 0:
            
            previous_score = scoring_array[row -1,col]
            score = previous_score + gap_penalty
            arrow = up_arrow
            
        else: 

            index1=ord(sequence1[row-1])-65
            index2=ord(sequence2[col-1])-65

            
            if(index1>=index2):
                alphabet_score=float(File_data[index1][index2])
                #print("alphabet_score "+ str(alphabet_score))
            else:
                alphabet_score=float(File_data[index2][index1])
                #print("alphabet_score "+ str(alphabet_score))
            
            cost=min(alphabet_score, gap_penalty)
            ################################
            
            cell_to_the_left = scoring_array[row,col-1]
            from_left_score = cell_to_the_left + cost#alphabet_score
            #print("from_left_score "+str(from_left_score))
             
            
            above_cell = scoring_array[row-1,col]
            from_above_score = above_cell +cost# alphabet_score
            #print("from_above_score "+str(from_above_score))
            
            diagonal_left_cell = scoring_array[row-1,col-1]
            

            if sequence1[row-1] == sequence2[col-1]:
                diagonal_left_cell_score = diagonal_left_cell + match_bonus
            else:
                diagonal_left_cell_score = diagonal_left_cell
                
            #print("diagonal_left_cell_score "+str(diagonal_left_cell_score))
            
            score = max([from_left_score,from_above_score,diagonal_left_cell_score])       
            #print("score is: " + str(score))

            
            #traceback path of current element
            if score == diagonal_left_cell_score:
                arrow = up_left_arrow            
            elif score == from_left_score:
                arrow = left_arrow     
            elif score == from_above_score:
                arrow = up_arrow                

                
                
        #print("input score "+str(score))
        traceback_array[row,col]=arrow    
        scoring_array[row,col] = score
        #print("saved score " + str(scoring_array[row,col]))

#traceback_array[0,1]='-'
#traceback_array[1,0]='-' 
display(table_from_array(scoring_array,row_labels,column_labels))  
display(table_from_array(traceback_array,row_labels,column_labels))            

In [9]:
def traceback_alignment(traceback_array,seq1,seq2,up_arrow = "\u2191" ,\
                        left_arrow="\u2190",up_left_arrow="\u2196",stop="-"):


    NUMBER_OF_ROWS = len(sequence1) + 1 
    NUMBER_OF_COLUMNS = len(sequence2) + 1 
    
    row = len(sequence1)
    col = len(sequence2)
    arrow = traceback_array[row,col]
    aligned_seq1 = ""
    aligned_seq2 = ""
    alignment_indicator = ""
    while arrow != "-":

            arrow = traceback_array[row,col]

            
            if arrow == up_arrow: 


                aligned_seq2 = "-"+aligned_seq2 
                aligned_seq1 = sequence1[row-1] + aligned_seq1
                alignment_indicator = " "+alignment_indicator
                row -=1
                            
            elif arrow == up_left_arrow:


                seq1_character = sequence1[row-1]
                seq2_character = sequence2[col-1]
                aligned_seq1 = sequence1[row-1] + aligned_seq1
                aligned_seq2 = sequence2[col-1] + aligned_seq2
                if seq1_character == seq2_character:
                    alignment_indicator = "|"+alignment_indicator
                else:
                    alignment_indicator = " "+alignment_indicator
                row -=1
                col -=1
                
            elif arrow == left_arrow:

                aligned_seq1 = "-"+aligned_seq1
                aligned_seq2 = sequence2[col-1] + aligned_seq2
                alignment_indicator = " "+alignment_indicator
                col -=1
                
            elif arrow == stop:
                break
                
                
    print(aligned_seq1)
    print(alignment_indicator)
    print(aligned_seq2)

            
    return aligned_seq1,aligned_seq2


traceback_alignment(traceback_array,sequence1,sequence2)

print(scoring_array[NUMBER_OF_ROWS-1][NUMBER_OF_COLUMNS-1])

MY------STRING-
        |||||| 
--GUITARSTRINGS
6.8999999999999995


In [10]:
##differentiating Needleman-Wunsch

In [11]:
#init
n=len(sequence1)
m=len(sequence2)
scoring_arr=np.zeros((n+1,m+1), dtype=float)  #scoring array

for i in range(1,n+2):
    scoring_arr[i-1,0]=gap_penalty*(i-1)
    
for i in range(1,m+2):
    scoring_arr[0,i-1]=gap_penalty*(i-1)    
    
    
gradient_arr=np.zeros((n+2,m+2), dtype=float)  #gradient array 
gradient_arr[n+1,m+1]=1.

backtracking_arr=np.zeros((n+2,m+2,3), dtype=float)  #backtracking arrray
backtracking_arr[n+1,m+1,1]=1.

print(scoring_arr)
print("\n")
print(gradient_arr)
print("\n")
print(backtracking_arr)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3]
 [0.1 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.3 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.4 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.6 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.7 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.8 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [12]:
#filing substition matrix by comparing seq1 and seq2
substitution_matrix=np.zeros((n,m), dtype=float)  
for i in range(n):
    for j in range(m):
        if sequence1[i]!=sequence2[j]:
            index1=ord(sequence1[i-1])-65
            #print(index1)
            index2=ord(sequence2[j-1])-65
            #print(index2)
            
            if(index1>=index2):
                alphabet_score=float(File_data[index1][index2])
                #print("alphabet_score "+ str(alphabet_score))
            else:
                alphabet_score=float(File_data[index2][index1])
                #print("alphabet_score "+ str(alphabet_score))            
            
            
            substitution_matrix[i,j]=alphabet_score  
        else:                           
            substitution_matrix[i,j]=1
    

row_labels = [label for label in sequence1]
column_labels = [label for label in sequence2]

display(table_from_array(substitution_matrix,row_labels,column_labels))

In [13]:
#smooth maximum
import math
def logsumexp(x, gamma):
    sum=0
    for i in x:
        sum+=math.exp(i*gamma)
    return (1/gamma)*(math.log(sum))


In [14]:
#check
import math
gamma=3
print(logsumexp([1,2,5], gamma))

5.000043181875014


In [15]:
#soft maximum
#mo argument still not implemented, ignore it

def max_argmax(x, gamma, mo):
    m=logsumexp(x,gamma)
    q=[]
    for element in x:
        q.append(math.exp((element/gamma)-(m/gamma)))
    return q

In [16]:
#mo argument still not implemented, ignore it


print(max_argmax([1,2,5], gamma, "EntropyMax"))

[-0.27106863553891536, 0.28105298042967086, 3.6278089898450245]


In [17]:
gamma=10
print(n)
print(m)
for i in range(n):
    for j in range(m):
        #calculating smooth_max vector 
        smooth_max=logsumexp([scoring_arr[i+1,j]   + gap_penalty,
                              scoring_arr[i,j]     + substitution_matrix[i,j],
                              scoring_arr[i,j+1]   + gap_penalty], gamma)
        #calculating softmax vector
        q=max_argmax([scoring_arr[i+1, j]          + gap_penalty,
                      scoring_arr[i, j]            + substitution_matrix[i,j],
                      scoring_arr[i, j+1]          + gap_penalty], gamma, "EntropyMax")
        
        scoring_arr[i+1,j+1]=smooth_max
        backtracking_arr[i+1][j+1][0]=q[0]
        backtracking_arr[i+1][j+1][1]=q[1]
        backtracking_arr[i+1][j+1][2]=q[2]
        
        

8
13


In [18]:
row_labels = [label for label in "-"+ sequence1]
column_labels = [label for label in "-"+ sequence2]
display(table_from_array(scoring_arr,row_labels,column_labels))

In [19]:
print(len(backtracking_arr))
print(len(backtracking_arr[0]))

print(backtracking_arr)

10
15
[[[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.         0.         0.        ]
  [0.96311525 1.00112881 0.96311525]
  [0.9592483  1.00613883 0.92031529]
  [1.00750932 0.9153671  0.92066624]
  [1.00884098 0.92357382 0.92111909]
  [1.01020212 0.95746999 0.92159   ]
  [1.01185342 0.94037882 0.92224087]
  [1.01289585 0.98177011 0.92235831]
  [1.01535654 0.96389445 0.92312459]
  [1.01733858 0.96137906 0.92403477]
  [1.01888007 0.98575504 0.92453388]
  [1.02178441 0.92837901 0.925

In [20]:
print(gradient_arr)
print(n)
print(m)
len(gradient_arr)
#calculating gradient
for i in range(n, -1, -1):
    for j in range(m, -1, -1):
        gradient_arr[i,j]= backtracking_arr[i,j+1,0]*gradient_arr[i,j+1]+backtracking_arr[i+1,j+1,1]*gradient_arr[i+1,j+1]+backtracking_arr[i+1,j,2]*gradient_arr[i+1,j]
        


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
8
13


In [21]:
print(gradient_arr)

[[5.86387943e+06 9.03527310e+06 4.72511058e+06 2.43606477e+06
  1.18306975e+06 5.20435830e+05 2.12593581e+05 7.58124284e+04
  2.39863017e+04 6.48577293e+03 1.41714122e+03 2.41076354e+02
  2.76883560e+01 1.56766046e+00 0.00000000e+00]
 [7.21061193e+06 5.85726768e+06 3.37334090e+06 1.77040814e+06
  8.72815732e+05 3.95941937e+05 1.65401112e+05 6.11690198e+04
  2.01190854e+04 5.63136789e+03 1.30072192e+03 2.31133766e+02
  2.80026515e+01 1.69959416e+00 0.00000000e+00]
 [1.92887737e+06 1.61392625e+06 1.00887744e+06 5.75735804e+05
  3.14691321e+05 1.62213613e+05 7.49134591e+04 3.07475264e+04
  1.11416602e+04 3.50492332e+03 9.07031878e+02 1.83488887e+02
  2.51611769e+01 1.73082362e+00 0.00000000e+00]
 [4.49696742e+05 3.84898754e+05 2.64660698e+05 1.66518214e+05
  9.67889437e+04 5.43697349e+04 2.91722175e+04 1.43434224e+04
  5.86552101e+03 2.07217601e+03 6.04691917e+02 1.37995612e+02
  2.21117685e+01 1.79229621e+00 0.00000000e+00]
 [8.37648455e+04 7.87855101e+04 5.66985055e+04 4.17343338e+04
  

In [22]:
value=scoring_arr[1:n, 0:m]
gradient=gradient_arr[1:n, 0:m]

In [23]:
print(value)

[[0.1        0.5708609  1.10139239 1.20144532 1.30152011 1.40246551
  1.50267311 1.6092876  1.71049689 1.81136147 1.91744191 2.01750565
  2.11849397]
 [0.2        0.67930992 1.24597162 1.46554732 1.71819234 1.95034057
  2.05189205 2.17293197 2.27636999 2.42450716 2.536155   2.64603661
  2.74677461]
 [0.3        0.78924583 1.37760411 1.7054363  1.88785155 2.10114295
  2.66969853 3.05770995 3.1578923  3.25797673 3.35807406 3.45819752
  3.60171735]
 [0.4        1.30166443 1.5342284  2.36555116 2.71419956 2.81446254
  3.02192536 3.21537084 4.05780322 4.15785875 4.25794069 4.35812109
  4.45831109]
 [0.5        1.40171897 1.84983327 2.48295673 2.94819556 3.71436118
  3.88377573 4.02697012 4.21290753 5.05789495 5.18924829 5.29007132
  5.3901015 ]
 [0.6        1.50179939 2.15055584 2.85677044 3.09260025 3.90212708
  4.68032544 4.91422373 5.01436848 5.24053572 6.05801743 6.1583428
  6.25840144]
 [0.7        1.60197629 2.25148848 2.95704426 3.85693442 4.05301955
  4.78114914 5.11942329 5.3251095

In [24]:
print(gradient)

[[7.21061193e+06 5.85726768e+06 3.37334090e+06 1.77040814e+06
  8.72815732e+05 3.95941937e+05 1.65401112e+05 6.11690198e+04
  2.01190854e+04 5.63136789e+03 1.30072192e+03 2.31133766e+02
  2.80026515e+01]
 [1.92887737e+06 1.61392625e+06 1.00887744e+06 5.75735804e+05
  3.14691321e+05 1.62213613e+05 7.49134591e+04 3.07475264e+04
  1.11416602e+04 3.50492332e+03 9.07031878e+02 1.83488887e+02
  2.51611769e+01]
 [4.49696742e+05 3.84898754e+05 2.64660698e+05 1.66518214e+05
  9.67889437e+04 5.43697349e+04 2.91722175e+04 1.43434224e+04
  5.86552101e+03 2.07217601e+03 6.04691917e+02 1.37995612e+02
  2.21117685e+01]
 [8.37648455e+04 7.87855101e+04 5.66985055e+04 4.17343338e+04
  2.76450874e+04 1.65676299e+04 9.41188659e+03 4.98759654e+03
  2.66409919e+03 1.08597743e+03 3.64166776e+02 9.66217084e+01
  1.82938995e+01]
 [1.25361004e+04 1.22063746e+04 9.76343524e+03 7.66111256e+03
  5.71321771e+03 4.14520814e+03 2.60887958e+03 1.53021312e+03
  8.59034258e+02 4.59673038e+02 1.86424865e+02 6.00769943e+0