In [1]:
from numpy import full
import numpy as np

sequence1 = "MYSTRING"
sequence2 = "GUITARSTRINGS"

alphabet="ABCDEFGHIJKLMNOPQRSTUVWZ"

NUMBER_OF_ROWS = len(sequence1) + 1
NUMBER_OF_COLUMNS = len(sequence2) + 1

scoring_array=np.zeros((NUMBER_OF_ROWS,NUMBER_OF_COLUMNS), dtype=float)

traceback_array=np.zeros((NUMBER_OF_ROWS,NUMBER_OF_COLUMNS), dtype=float)

#scoring_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],0.00000)
print("Scoring array:\n",scoring_array)


#traceback_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],"-")
print("Traceback array:\n",traceback_array)


Scoring array:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Traceback array:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [2]:
import numpy
numpy.random.seed(3)
numpy.random.rand()

0.5507979025745755

In [3]:
import numpy as np
alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
print(len(alphabet))
File_data=np.zeros((26,26), dtype=float)
for i in range (26):
    for j in range (26):
        File_data[i][j]=numpy.random.rand()

####delete
#File_data=np.zeros((26,26), dtype=float)
for i in range (26):
    File_data[i][i]=1

print(NUMBER_OF_ROWS)
print(NUMBER_OF_COLUMNS)

print(len(File_data))
#print(File_data)

26
9
14
26


In [4]:
from IPython.core.display import HTML,display
import pandas as pd

def table_from_array(data_array, row_labels,col_labels):
    """Show an HTML table from a 2d numpy array"""
    df = pd.DataFrame(data_array,index=row_labels,columns=col_labels)
    table_html = df.to_html()
    return HTML(table_html)

In [5]:
row_labels = [label for label in "-"+ sequence1]
column_labels = [label for label in "-"+ sequence2]

alpha_table_rows=[label for label in alphabet]
alpha_table_cols=[label for label in alphabet]

print("Alphabet array:")
display(table_from_array(File_data,alpha_table_rows,alpha_table_cols))

print("Scoring array:")
display(table_from_array(scoring_array,row_labels,column_labels))
print("Traceback array:")
display(table_from_array(traceback_array,row_labels,column_labels))

Alphabet array:


Scoring array:


Traceback array:


In [6]:
up_arrow = "\u2191"
right_arrow = "\u2192"
down_arrow = "\u2193"
left_arrow = "\u2190"
down_right_arrow = "\u2198"
up_left_arrow = "\u2196"

print("Up arrow",up_arrow)
print("Right arrow",right_arrow)
print("Down arrow",down_arrow)
print("Left arrow",left_arrow)
print("Down Left arrow",down_right_arrow)
print("Up Left arrow",up_left_arrow)


Up arrow ↑
Right arrow →
Down arrow ↓
Left arrow ←
Down Left arrow ↘
Up Left arrow ↖


In [7]:

NUMBER_OF_ROWS = len(sequence1) + 1 
NUMBER_OF_COLUMNS = len(sequence2) + 1
row_labels = [label for label in "-"+sequence1]
column_labels = [label for label in "-"+sequence2]


scoring_array=np.zeros((NUMBER_OF_ROWS,NUMBER_OF_COLUMNS), dtype=float)



traceback_array = full([NUMBER_OF_ROWS,NUMBER_OF_COLUMNS],"-")


arrow = "-"

match_bonus = 1
gap_penalty=0.1


In [8]:
for row in range(NUMBER_OF_ROWS):
    for col in range(NUMBER_OF_COLUMNS):    
        #set first row and column to zero
        if row ==0 and col == 0:
            score=0
            arrow='-'
        elif row == 0:

            previous_score = scoring_array[row,col - 1]
            
            score = previous_score + gap_penalty
            arrow = left_arrow
        elif col == 0:
            
            previous_score = scoring_array[row -1,col]
            score = previous_score + gap_penalty
            arrow = up_arrow
            

            
        else: 

            index1=ord(sequence1[row-1])-65
            index2=ord(sequence2[col-1])-65

            
            if(index1>=index2):
                alphabet_score=float(File_data[index1][index2])
                #print("alphabet_score "+ str(alphabet_score))
            else:
                alphabet_score=float(File_data[index2][index1])
                #print("alphabet_score "+ str(alphabet_score))
            
            cost=min(alphabet_score, gap_penalty)
            ################################
            
            cell_to_the_left = scoring_array[row,col-1]
            from_left_score = cell_to_the_left + cost#alphabet_score
            #print("from_left_score "+str(from_left_score))
             
            
            above_cell = scoring_array[row-1,col]
            from_above_score = above_cell +cost# alphabet_score
            #print("from_above_score "+str(from_above_score))
            
            diagonal_left_cell = scoring_array[row-1,col-1]
            

            if sequence1[row-1] == sequence2[col-1]:
                diagonal_left_cell_score = diagonal_left_cell + match_bonus
            else:
                diagonal_left_cell_score = diagonal_left_cell
                
            #print("diagonal_left_cell_score "+str(diagonal_left_cell_score))
            
            score = max([from_left_score,from_above_score,diagonal_left_cell_score])       
            #print("score is: " + str(score))

            
            #traceback path of current element
            if score == diagonal_left_cell_score:
                arrow = up_left_arrow            
            elif score == from_left_score:
                arrow = left_arrow     
            elif score == from_above_score:
                arrow = up_arrow                

                
                
        #print("input score "+str(score))
        traceback_array[row,col]=arrow
        scoring_array[row,col] = score
        #print("saved score " + str(scoring_array[row,col]))

#traceback_array[0,1]='-'
#traceback_array[1,0]='-' 
display(table_from_array(scoring_array,row_labels,column_labels))  
display(table_from_array(traceback_array,row_labels,column_labels))            

In [9]:
def traceback_alignment(traceback_array,seq1,seq2,up_arrow = "\u2191" ,\
                        left_arrow="\u2190",up_left_arrow="\u2196",stop="-"):


    NUMBER_OF_ROWS = len(sequence1) + 1 
    NUMBER_OF_COLUMNS = len(sequence2) + 1 
    
    row = len(sequence1)
    col = len(sequence2)
    arrow = traceback_array[row,col]
    aligned_seq1 = ""
    aligned_seq2 = ""
    alignment_indicator = ""
    while arrow != "-":

            arrow = traceback_array[row,col]

            
            if arrow == up_arrow: 


                aligned_seq2 = "-"+aligned_seq2 
                aligned_seq1 = sequence1[row-1] + aligned_seq1
                alignment_indicator = " "+alignment_indicator
                row -=1
                            
            elif arrow == up_left_arrow:


                seq1_character = sequence1[row-1]
                seq2_character = sequence2[col-1]
                aligned_seq1 = sequence1[row-1] + aligned_seq1
                aligned_seq2 = sequence2[col-1] + aligned_seq2
                if seq1_character == seq2_character:
                    alignment_indicator = "|"+alignment_indicator
                else:
                    alignment_indicator = " "+alignment_indicator
                row -=1
                col -=1
                
            elif arrow == left_arrow:

                aligned_seq1 = "-"+aligned_seq1
                aligned_seq2 = sequence2[col-1] + aligned_seq2
                alignment_indicator = " "+alignment_indicator
                col -=1
                
            elif arrow == stop:
                break
                
                
    print(aligned_seq1)
    print(alignment_indicator)
    print(aligned_seq2)

            
    return aligned_seq1,aligned_seq2


traceback_alignment(traceback_array,sequence1,sequence2)

print(scoring_array[NUMBER_OF_ROWS-1][NUMBER_OF_COLUMNS-1])

MY------STRING-
        |||||| 
--GUITARSTRINGS
6.8999999999999995


In [10]:
##differentiating Needleman-Wunsch

In [11]:
#init
#seq1= MYSTRING
# GUITARSTRINGS
n=len(sequence1)
m=len(sequence2)
scoring_arr=np.zeros((n+1,m+1), dtype=float)  #scoring array

for i in range(1,n+2):
    scoring_arr[i-1,0]=gap_penalty*(i-1)
    
for i in range(1,m+2):
    scoring_arr[0,i-1]=gap_penalty*(i-1)    
    
    
gradient_arr=np.zeros((n+2,m+2), dtype=float)  #gradient array 
gradient_arr[n+1,m+1]=1.

backtracking_arr=np.zeros((n+2,m+2,3), dtype=float)  #backtracking arrray
backtracking_arr[n+1,m+1,1]=1.

print(scoring_arr)
print("\n")
print(gradient_arr)
print("\n")
print(backtracking_arr)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3]
 [0.1 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.3 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.4 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.6 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.7 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.8 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [12]:
#filing substition matrix by comparing seq1 and seq2
substitution_matrix=np.zeros((n,m), dtype=float)  
for i in range(n):
    for j in range(m):
        if sequence1[i]!=sequence2[j]:
            index1=ord(sequence1[i-1])-65
            #print(index1)
            index2=ord(sequence2[j-1])-65
            #print(index2)
            
            if(index1>=index2):
                alphabet_score=float(File_data[index1][index2])
                #print("alphabet_score "+ str(alphabet_score))
            else:
                alphabet_score=float(File_data[index2][index1])
                #print("alphabet_score "+ str(alphabet_score))            
            
            
            substitution_matrix[i,j]=alphabet_score  
        else:                           
            substitution_matrix[i,j]=1
    

row_labels = [label for label in sequence1]
column_labels = [label for label in sequence2]

display(table_from_array(substitution_matrix,row_labels,column_labels))

In [13]:
#smooth maximum
#import math
#def logsumexp(x, gamma):
##    sum1=0
#    for i in x:
#        sum1+=math.exp(i*gamma)
#    return (1/math.log(gamma))*(math.log(sum1))


In [14]:
#check
#from scipy.special import logsumexp
import math

import numpy as np

 

def logsumexp(x, gamma):

    _sum = 0

    x = np.array(x)

    x = x * gamma

    for i in x:

        _sum += math.exp(i)

    return math.log(_sum) / gamma

import math
gamma=1
print(logsumexp([1,2,5], gamma) )

5.065883903757429


In [15]:
#soft maximum
#mo argument still not implemented, ignore it

def max_argmax(x, gamma, mo):
    m=logsumexp(x,gamma)
    q=[]
    for element in x:
        q.append(math.exp((element)-(m)))
    return q
    
    


In [16]:
#they need to sum to 1

print(max_argmax([1,2,5], gamma, "EntropyMax"))



[0.017147825545520388, 0.04661262257797389, 0.9362395518765056]


In [17]:
gamma=10
print(n)
print(m)
for i in range(n):
    for j in range(m):
        #calculating smooth_max vector 
        smooth_max=logsumexp([scoring_arr[i+1,j]   + gap_penalty,
                              scoring_arr[i,j]     + substitution_matrix[i,j],
                              scoring_arr[i,j+1]   + gap_penalty], gamma)
        #calculating softmax vector
        q=max_argmax([scoring_arr[i+1, j]          + gap_penalty,
                      scoring_arr[i, j]            + substitution_matrix[i,j],
                      scoring_arr[i, j+1]          + gap_penalty], gamma, "EntropyMax")
        
        scoring_arr[i+1,j+1]=smooth_max
        backtracking_arr[i+1][j+1][0]=q[0]
        backtracking_arr[i+1][j+1][1]=q[1]
        backtracking_arr[i+1][j+1][2]=q[2]
        
        

8
13


In [18]:
row_labels = [label for label in "-"+ sequence1]
column_labels = [label for label in "-"+ sequence2]
display(table_from_array(scoring_arr,row_labels,column_labels))

In [19]:
print(len(backtracking_arr))
print(len(backtracking_arr[0]))

print(backtracking_arr)

10
15
[[[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.         0.         0.        ]
  [0.69013994 0.99498605 0.69013994]
  [0.65016344 0.99860857 0.44870376]
  [0.99994708 0.42635242 0.44868001]
  [0.99992522 0.4592332  0.44864645]
  [0.99905504 0.6249123  0.4482225 ]
  [0.99979242 0.52995132 0.44812946]
  [0.99340734 0.75929978 0.4451751 ]
  [0.99879144 0.64104056 0.44463708]
  [0.99913579 0.61937775 0.44425282]
  [0.99393801 0.75313338 0.44155976]
  [0.99993627 0.45195047 0.441

In [20]:
print(gradient_arr)
print(n)
print(m)
len(gradient_arr)
#calculating gradient
for i in range(n, -1, -1):
    for j in range(m, -1, -1):
        gradient_arr[i,j]= backtracking_arr[i,j+1,0]*gradient_arr[i,j+1]+backtracking_arr[i+1,j+1,1]*gradient_arr[i+1,j+1]+backtracking_arr[i+1,j,2]*gradient_arr[i+1,j]
        


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
8
13


In [21]:
print(gradient_arr)

[[1.78828303e+04 2.68514637e+04 9.86402456e+03 5.39859571e+03
  2.87565312e+03 1.13754281e+03 4.80908645e+02 1.42755895e+02
  4.25579312e+01 1.15229390e+01 2.27810412e+00 4.12147645e-01
  4.87434340e-02 2.33353918e-03 0.00000000e+00]
 [1.59680972e+04 1.79729457e+04 1.44677469e+04 7.90963544e+03
  4.02780201e+03 1.70999041e+03 7.00227780e+02 2.20092186e+02
  6.98494583e+01 1.85674610e+01 4.34755943e+00 7.93000222e-01
  9.87315704e-02 5.62032749e-03 0.00000000e+00]
 [4.03140681e+03 4.73431560e+03 4.30032082e+03 2.61928650e+03
  1.70985620e+03 1.10924053e+03 5.20506667e+02 1.77386725e+02
  5.61972902e+01 1.76758075e+01 4.59473836e+00 1.04365813e+00
  1.45485176e-01 9.14900830e-03 0.00000000e+00]
 [9.21701849e+02 1.02671217e+03 1.16668612e+03 8.83021478e+02
  5.05853955e+02 3.44234838e+02 2.62750370e+02 1.91369775e+02
  6.56545235e+01 2.18947184e+01 6.02734454e+00 1.37570101e+00
  2.47946405e-01 2.09782919e-02 0.00000000e+00]
 [1.13368842e+02 2.26411397e+02 1.92468361e+02 2.81823656e+02
  

In [22]:
value=scoring_arr[1:n, 0:m]
gradient=gradient_arr[1:n, 0:m]

In [23]:
print(value)

[[0.1        0.5708609  1.10139239 1.20144532 1.30152011 1.40246551
  1.50267311 1.6092876  1.71049689 1.81136147 1.91744191 2.01750565
  2.11849397]
 [0.2        0.67930992 1.24597162 1.46554732 1.71819234 1.95034057
  2.05189205 2.17293197 2.27636999 2.42450716 2.536155   2.64603661
  2.74677461]
 [0.3        0.78924583 1.37760411 1.7054363  1.88785155 2.10114295
  2.66969853 3.05770995 3.1578923  3.25797673 3.35807406 3.45819752
  3.60171735]
 [0.4        1.30166443 1.5342284  2.36555116 2.71419956 2.81446254
  3.02192536 3.21537084 4.05780322 4.15785875 4.25794069 4.35812109
  4.45831109]
 [0.5        1.40171897 1.84983327 2.48295673 2.94819556 3.71436118
  3.88377573 4.02697012 4.21290753 5.05789495 5.18924829 5.29007132
  5.3901015 ]
 [0.6        1.50179939 2.15055584 2.85677044 3.09260025 3.90212708
  4.68032544 4.91422373 5.01436848 5.24053572 6.05801743 6.1583428
  6.25840144]
 [0.7        1.60197629 2.25148848 2.95704426 3.85693442 4.05301955
  4.78114914 5.11942329 5.3251095

In [24]:
print(gradient)

[[1.59680972e+04 1.79729457e+04 1.44677469e+04 7.90963544e+03
  4.02780201e+03 1.70999041e+03 7.00227780e+02 2.20092186e+02
  6.98494583e+01 1.85674610e+01 4.34755943e+00 7.93000222e-01
  9.87315704e-02]
 [4.03140681e+03 4.73431560e+03 4.30032082e+03 2.61928650e+03
  1.70985620e+03 1.10924053e+03 5.20506667e+02 1.77386725e+02
  5.61972902e+01 1.76758075e+01 4.59473836e+00 1.04365813e+00
  1.45485176e-01]
 [9.21701849e+02 1.02671217e+03 1.16668612e+03 8.83021478e+02
  5.05853955e+02 3.44234838e+02 2.62750370e+02 1.91369775e+02
  6.56545235e+01 2.18947184e+01 6.02734454e+00 1.37570101e+00
  2.47946405e-01]
 [1.13368842e+02 2.26411397e+02 1.92468361e+02 2.81823656e+02
  2.58479382e+02 1.58547140e+02 9.92036062e+01 5.74678476e+01
  7.14859661e+01 2.70261022e+01 7.98866726e+00 2.03895966e+00
  4.29049945e-01]
 [1.33815211e+01 2.74614229e+01 3.08639074e+01 3.85080654e+01
  4.38676169e+01 6.16175514e+01 4.47593796e+01 2.88438261e+01
  2.15106318e+01 2.41062057e+01 9.35877621e+00 3.03975416e+0